server: 
  port: 9527
 
spring: 
  application:
    name: cloudcampusecology-gateway
  devtools:
    restart:
      enabled: true
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #thirdparty 模块
        - id: service-thirdparty
          uri: lb://service-thirdparty
          predicates:
            - Path=/thirdparty/**
          filters:
            - StripPrefix=1
        #system 模块
        - id: service-daka
          uri: lb://service-daka
          predicates:
            - Path=/daka/**
          filters:
            - StripPrefix=1


eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://localhost:7001/eureka
       #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance:
    instance-id:  ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址      

hystrix:
    command:
      default:  #default全局有效，service id指定应用有效
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 5000 #断路器超时时间，默认1000ms
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'